/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ActualizarCatalogoDto } from './models/ActualizarCatalogoDto';
export type { ActualizarCiudadDto } from './models/ActualizarCiudadDto';
export type { ActualizarPaisDto } from './models/ActualizarPaisDto';
export type { ActualizarProvinciaDto } from './models/ActualizarProvinciaDto';
export type { ApiErrorResponse } from './models/ApiErrorResponse';
export type { AutenticacionLoginInternoRequest } from './models/AutenticacionLoginInternoRequest';
export type { AutenticacionLoginInternoResponse } from './models/AutenticacionLoginInternoResponse';
export type { AutenticacionLoginInternoResponseApiResponse } from './models/AutenticacionLoginInternoResponseApiResponse';
export type { AutenticacionLoginRequest } from './models/AutenticacionLoginRequest';
export type { AutenticacionLoginResponse } from './models/AutenticacionLoginResponse';
export type { AutenticacionLoginResponseApiResponse } from './models/AutenticacionLoginResponseApiResponse';
export type { AutenticacionRegistroClienteRequest } from './models/AutenticacionRegistroClienteRequest';
export type { BooleanApiResponse } from './models/BooleanApiResponse';
export type { BuscarCitasAdministradorRequest } from './models/BuscarCitasAdministradorRequest';
export type { BuscarCitasAdministradorResponse } from './models/BuscarCitasAdministradorResponse';
export type { BuscarCitasAdministradorResponseApiResponse } from './models/BuscarCitasAdministradorResponseApiResponse';
export type { BuscarClienteEmpresaRequest } from './models/BuscarClienteEmpresaRequest';
export type { BuscarClienteNaturalRequest } from './models/BuscarClienteNaturalRequest';
export type { CambiarPasswordRequest } from './models/CambiarPasswordRequest';
export type { CatalogoDto } from './models/CatalogoDto';
export type { CatalogoDtoApiResponse } from './models/CatalogoDtoApiResponse';
export type { CatalogoDtoIEnumerableApiResponse } from './models/CatalogoDtoIEnumerableApiResponse';
export type { CitaAdministradorCreatedResponse } from './models/CitaAdministradorCreatedResponse';
export type { CitaAdministradorCreatedResponseApiResponse } from './models/CitaAdministradorCreatedResponseApiResponse';
export type { CitaAdministradorResponse } from './models/CitaAdministradorResponse';
export type { CitaAdministradorResponseIEnumerableApiResponse } from './models/CitaAdministradorResponseIEnumerableApiResponse';
export type { CitaRequest } from './models/CitaRequest';
export type { CitaResponse } from './models/CitaResponse';
export type { CitaResponseApiResponse } from './models/CitaResponseApiResponse';
export type { CitaResponseListApiResponse } from './models/CitaResponseListApiResponse';
export type { CiudadDto } from './models/CiudadDto';
export type { CiudadDtoApiResponse } from './models/CiudadDtoApiResponse';
export type { CiudadDtoIEnumerableApiResponse } from './models/CiudadDtoIEnumerableApiResponse';
export type { ClienteEmpresaData } from './models/ClienteEmpresaData';
export type { ClienteEmpresaDetalleResponse } from './models/ClienteEmpresaDetalleResponse';
export type { ClienteEmpresaDetalleResponseApiResponse } from './models/ClienteEmpresaDetalleResponseApiResponse';
export type { ClienteEmpresaListaResponse } from './models/ClienteEmpresaListaResponse';
export type { ClienteEmpresaListaResponseIEnumerableApiResponse } from './models/ClienteEmpresaListaResponseIEnumerableApiResponse';
export type { ClienteEmpresaListaResponsePagedResponse } from './models/ClienteEmpresaListaResponsePagedResponse';
export type { ClienteInternoRequest } from './models/ClienteInternoRequest';
export type { ClienteInternoResponse } from './models/ClienteInternoResponse';
export type { ClienteInternoResponseApiResponse } from './models/ClienteInternoResponseApiResponse';
export type { ClienteNaturalData } from './models/ClienteNaturalData';
export type { ClienteNaturalDetalleResponse } from './models/ClienteNaturalDetalleResponse';
export type { ClienteNaturalDetalleResponseApiResponse } from './models/ClienteNaturalDetalleResponseApiResponse';
export type { ClienteNaturalListaResponse } from './models/ClienteNaturalListaResponse';
export type { ClienteNaturalListaResponseIEnumerableApiResponse } from './models/ClienteNaturalListaResponseIEnumerableApiResponse';
export type { ClienteNaturalListaResponsePagedResponse } from './models/ClienteNaturalListaResponsePagedResponse';
export type { ClienteSelectorResponse } from './models/ClienteSelectorResponse';
export type { ClienteSelectorResponseIEnumerableApiResponse } from './models/ClienteSelectorResponseIEnumerableApiResponse';
export type { ClientesEmpresaRequest } from './models/ClientesEmpresaRequest';
export type { ClientesEmpresaResponse } from './models/ClientesEmpresaResponse';
export type { ClientesEmpresaResponseApiResponse } from './models/ClientesEmpresaResponseApiResponse';
export type { ClientesNaturalRequest } from './models/ClientesNaturalRequest';
export type { ClientesNaturalResponse } from './models/ClientesNaturalResponse';
export type { ClientesNaturalResponseApiResponse } from './models/ClientesNaturalResponseApiResponse';
export type { ContactoDirectoClienteDetalleResponse } from './models/ContactoDirectoClienteDetalleResponse';
export type { ContactoDirectoClienteDetalleResponseListApiResponse } from './models/ContactoDirectoClienteDetalleResponseListApiResponse';
export type { ContactoDirectoRequest } from './models/ContactoDirectoRequest';
export type { ContactoDirectoResponse } from './models/ContactoDirectoResponse';
export type { ContactoDirectoResponseApiResponse } from './models/ContactoDirectoResponseApiResponse';
export type { ContactoDirectoResponseListApiResponse } from './models/ContactoDirectoResponseListApiResponse';
export type { ContactoEmpresaClienteDetalleResponse } from './models/ContactoEmpresaClienteDetalleResponse';
export type { ContactoEmpresaClienteDetalleResponseListApiResponse } from './models/ContactoEmpresaClienteDetalleResponseListApiResponse';
export type { ContactosEmpresaRequest } from './models/ContactosEmpresaRequest';
export type { ContactosEmpresaResponse } from './models/ContactosEmpresaResponse';
export type { ContactosEmpresaResponseApiResponse } from './models/ContactosEmpresaResponseApiResponse';
export type { ContactosEmpresaResponseListApiResponse } from './models/ContactosEmpresaResponseListApiResponse';
export type { CrearCatalogoDto } from './models/CrearCatalogoDto';
export type { CrearCitaAdministradorRequest } from './models/CrearCitaAdministradorRequest';
export type { CrearCiudadDto } from './models/CrearCiudadDto';
export type { CrearClienteAdminResponse } from './models/CrearClienteAdminResponse';
export type { CrearClienteAdminResponseApiResponse } from './models/CrearClienteAdminResponseApiResponse';
export type { CrearClienteEmpresaAdminRequest } from './models/CrearClienteEmpresaAdminRequest';
export type { CrearClienteNaturalAdminRequest } from './models/CrearClienteNaturalAdminRequest';
export type { CrearEmpleadoResponse } from './models/CrearEmpleadoResponse';
export type { CrearEmpleadoResponseApiResponse } from './models/CrearEmpleadoResponseApiResponse';
export type { CrearPaisDto } from './models/CrearPaisDto';
export type { CrearProvinciaDto } from './models/CrearProvinciaDto';
export type { DireccionClienteDetalleResponse } from './models/DireccionClienteDetalleResponse';
export type { DireccionClienteDetalleResponseListApiResponse } from './models/DireccionClienteDetalleResponseListApiResponse';
export type { DireccionRequest } from './models/DireccionRequest';
export type { DireccionResponse } from './models/DireccionResponse';
export type { DireccionResponseListApiResponse } from './models/DireccionResponseListApiResponse';
export type { EstadoEmpleadoRequest } from './models/EstadoEmpleadoRequest';
export type { ObjectApiResponse } from './models/ObjectApiResponse';
export type { PaginationInfo } from './models/PaginationInfo';
export type { PaisDto } from './models/PaisDto';
export type { PaisDtoApiResponse } from './models/PaisDtoApiResponse';
export type { PaisDtoIEnumerableApiResponse } from './models/PaisDtoIEnumerableApiResponse';
export type { ProvinciaDto } from './models/ProvinciaDto';
export type { ProvinciaDtoApiResponse } from './models/ProvinciaDtoApiResponse';
export type { ProvinciaDtoIEnumerableApiResponse } from './models/ProvinciaDtoIEnumerableApiResponse';
export type { RestablecerPasswordRequest } from './models/RestablecerPasswordRequest';
export type { SolicitarRestablecimientoRequest } from './models/SolicitarRestablecimientoRequest';
export type { StringIEnumerableApiResponse } from './models/StringIEnumerableApiResponse';
export type { TipoClienteResponse } from './models/TipoClienteResponse';
export type { TipoClienteResponseApiResponse } from './models/TipoClienteResponseApiResponse';

export { AdministradorService } from './services/AdministradorService';
export { AutenticacionService } from './services/AutenticacionService';
export { CatalogosService } from './services/CatalogosService';
export { CitasService } from './services/CitasService';
export { ClienteInternoService } from './services/ClienteInternoService';
export { ClientesService } from './services/ClientesService';
export { ContactosDirectosService } from './services/ContactosDirectosService';
export { ContactosEmpresaService } from './services/ContactosEmpresaService';
export { DiagnosticoService } from './services/DiagnosticoService';
export { DireccionesService } from './services/DireccionesService';
export { LocalidadesService } from './services/LocalidadesService';
