/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ActivoCreateUpdateRequest } from './models/ActivoCreateUpdateRequest';
export type { ActivoDto } from './models/ActivoDto';
export type { ActivoDtoPagedResponse } from './models/ActivoDtoPagedResponse';
export type { ActualizarCatalogoDto } from './models/ActualizarCatalogoDto';
export type { ActualizarCiudadDto } from './models/ActualizarCiudadDto';
export type { ActualizarClienteEmpresaDto } from './models/ActualizarClienteEmpresaDto';
export type { ActualizarClienteNaturalDto } from './models/ActualizarClienteNaturalDto';
export type { ActualizarContactoDirectoDto } from './models/ActualizarContactoDirectoDto';
export type { ActualizarContactoEmpresaDto } from './models/ActualizarContactoEmpresaDto';
export type { ActualizarDireccionDto } from './models/ActualizarDireccionDto';
export type { ActualizarEstadoComponenteRequest } from './models/ActualizarEstadoComponenteRequest';
export type { ActualizarMisDatosRequest } from './models/ActualizarMisDatosRequest';
export type { ActualizarMisDatosResponse } from './models/ActualizarMisDatosResponse';
export type { ActualizarMisDatosResponseApiResponse } from './models/ActualizarMisDatosResponseApiResponse';
export type { ActualizarPaisDto } from './models/ActualizarPaisDto';
export type { ActualizarParteRequest } from './models/ActualizarParteRequest';
export type { ActualizarProvinciaDto } from './models/ActualizarProvinciaDto';
export type { AgregarDatosFaltantesOrdenRequest } from './models/AgregarDatosFaltantesOrdenRequest';
export type { ApiErrorResponse } from './models/ApiErrorResponse';
export type { AsignarTecnicoRequest } from './models/AsignarTecnicoRequest';
export type { AsociarActivoOrdenRequest } from './models/AsociarActivoOrdenRequest';
export type { AutenticacionLoginInternoRequest } from './models/AutenticacionLoginInternoRequest';
export type { AutenticacionLoginInternoResponse } from './models/AutenticacionLoginInternoResponse';
export type { AutenticacionLoginInternoResponseApiResponse } from './models/AutenticacionLoginInternoResponseApiResponse';
export type { AutenticacionLoginRequest } from './models/AutenticacionLoginRequest';
export type { AutenticacionLoginResponse } from './models/AutenticacionLoginResponse';
export type { AutenticacionLoginResponseApiResponse } from './models/AutenticacionLoginResponseApiResponse';
export type { BuscarInspectorMantenimientoRequest } from './models/BuscarInspectorMantenimientoRequest';
export type { BuscarTecnicoMantenimientoRequest } from './models/BuscarTecnicoMantenimientoRequest';
export type { CambiarEstadoMantenimientoRequest } from './models/CambiarEstadoMantenimientoRequest';
export type { CambiarPasswordRequest } from './models/CambiarPasswordRequest';
export type { CancelarMantenimientoRequest } from './models/CancelarMantenimientoRequest';
export type { CargaTecnicoResponse } from './models/CargaTecnicoResponse';
export type { CatalogoDto } from './models/CatalogoDto';
export type { CatalogoDtoApiResponse } from './models/CatalogoDtoApiResponse';
export type { CatalogoDtoIEnumerableApiResponse } from './models/CatalogoDtoIEnumerableApiResponse';
export type { CitaRequest } from './models/CitaRequest';
export type { CitaResponse } from './models/CitaResponse';
export type { CitaResponseApiResponse } from './models/CitaResponseApiResponse';
export type { CitaResponseListApiResponse } from './models/CitaResponseListApiResponse';
export type { CiudadDto } from './models/CiudadDto';
export type { CiudadDtoApiResponse } from './models/CiudadDtoApiResponse';
export type { CiudadDtoIEnumerableApiResponse } from './models/CiudadDtoIEnumerableApiResponse';
export type { ClienteEmpresaDto } from './models/ClienteEmpresaDto';
export type { ClienteEmpresaDtoApiResponse } from './models/ClienteEmpresaDtoApiResponse';
export type { ClienteInternoRequest } from './models/ClienteInternoRequest';
export type { ClienteInternoResponse } from './models/ClienteInternoResponse';
export type { ClienteInternoResponseApiResponse } from './models/ClienteInternoResponseApiResponse';
export type { ClienteInternoResponsePagedResponse } from './models/ClienteInternoResponsePagedResponse';
export type { ClienteNaturalDto } from './models/ClienteNaturalDto';
export type { ClienteNaturalDtoApiResponse } from './models/ClienteNaturalDtoApiResponse';
export type { ClienteSelectorResponse } from './models/ClienteSelectorResponse';
export type { ClienteSelectorResponseIEnumerableApiResponse } from './models/ClienteSelectorResponseIEnumerableApiResponse';
export type { ClientesEmpresaRequest } from './models/ClientesEmpresaRequest';
export type { ClientesEmpresaResponse } from './models/ClientesEmpresaResponse';
export type { ClientesEmpresaResponseApiResponse } from './models/ClientesEmpresaResponseApiResponse';
export type { ClientesNaturalRequest } from './models/ClientesNaturalRequest';
export type { ClientesNaturalResponse } from './models/ClientesNaturalResponse';
export type { ClientesNaturalResponseApiResponse } from './models/ClientesNaturalResponseApiResponse';
export type { ComponenteDisponibleResponse } from './models/ComponenteDisponibleResponse';
export type { ComponenteDisponibleResponseListApiResponse } from './models/ComponenteDisponibleResponseListApiResponse';
export type { ContactoDirectoDto } from './models/ContactoDirectoDto';
export type { ContactoDirectoDtoApiResponse } from './models/ContactoDirectoDtoApiResponse';
export type { ContactoDirectoDtoPagedResponse } from './models/ContactoDirectoDtoPagedResponse';
export type { ContactoDirectoDtoPagedResponseApiResponse } from './models/ContactoDirectoDtoPagedResponseApiResponse';
export type { ContactoDirectoRequest } from './models/ContactoDirectoRequest';
export type { ContactoDirectoResponse } from './models/ContactoDirectoResponse';
export type { ContactoDirectoResponseApiResponse } from './models/ContactoDirectoResponseApiResponse';
export type { ContactoDirectoResponsePagedResponse } from './models/ContactoDirectoResponsePagedResponse';
export type { ContactoEmpresaDto } from './models/ContactoEmpresaDto';
export type { ContactoEmpresaDtoApiResponse } from './models/ContactoEmpresaDtoApiResponse';
export type { ContactoEmpresaDtoPagedResponse } from './models/ContactoEmpresaDtoPagedResponse';
export type { ContactoEmpresaDtoPagedResponseApiResponse } from './models/ContactoEmpresaDtoPagedResponseApiResponse';
export type { ContactosEmpresaRequest } from './models/ContactosEmpresaRequest';
export type { ContactosEmpresaResponse } from './models/ContactosEmpresaResponse';
export type { ContactosEmpresaResponseApiResponse } from './models/ContactosEmpresaResponseApiResponse';
export type { ContactosEmpresaResponsePagedResponse } from './models/ContactosEmpresaResponsePagedResponse';
export type { ContactosEmpresaResponsePagedResponseApiResponse } from './models/ContactosEmpresaResponsePagedResponseApiResponse';
export type { CrearActivoYAsociarRequest } from './models/CrearActivoYAsociarRequest';
export type { CrearCatalogoDto } from './models/CrearCatalogoDto';
export type { CrearCitaClienteRequest } from './models/CrearCitaClienteRequest';
export type { CrearCitaClienteResponse } from './models/CrearCitaClienteResponse';
export type { CrearCiudadDto } from './models/CrearCiudadDto';
export type { CrearClienteEmpresaDto } from './models/CrearClienteEmpresaDto';
export type { CrearClienteEmpresaResponseDto } from './models/CrearClienteEmpresaResponseDto';
export type { CrearClienteEmpresaResponseDtoApiResponse } from './models/CrearClienteEmpresaResponseDtoApiResponse';
export type { CrearClienteNaturalDto } from './models/CrearClienteNaturalDto';
export type { CrearClienteNaturalResponseDto } from './models/CrearClienteNaturalResponseDto';
export type { CrearClienteNaturalResponseDtoApiResponse } from './models/CrearClienteNaturalResponseDtoApiResponse';
export type { CrearContactoDirectoDto } from './models/CrearContactoDirectoDto';
export type { CrearContactoEmpresaDto } from './models/CrearContactoEmpresaDto';
export type { CrearDireccionDto } from './models/CrearDireccionDto';
export type { CrearEmpleadoResponse } from './models/CrearEmpleadoResponse';
export type { CrearEmpleadoResponseApiResponse } from './models/CrearEmpleadoResponseApiResponse';
export type { CrearOrdenConNumeroRequest } from './models/CrearOrdenConNumeroRequest';
export type { CrearPaisDto } from './models/CrearPaisDto';
export type { CrearParteRequest } from './models/CrearParteRequest';
export type { CrearProvinciaDto } from './models/CrearProvinciaDto';
export type { DireccionDetalleResponse } from './models/DireccionDetalleResponse';
export type { DireccionDetalleResponseApiResponse } from './models/DireccionDetalleResponseApiResponse';
export type { DireccionDto } from './models/DireccionDto';
export type { DireccionDtoApiResponse } from './models/DireccionDtoApiResponse';
export type { DireccionRequest } from './models/DireccionRequest';
export type { DireccionResponse } from './models/DireccionResponse';
export type { DireccionResponsePagedResponse } from './models/DireccionResponsePagedResponse';
export type { EditarCitaClienteRequest } from './models/EditarCitaClienteRequest';
export type { EditarCitaRequest } from './models/EditarCitaRequest';
export type { EstadoClienteResponseDto } from './models/EstadoClienteResponseDto';
export type { EstadoClienteResponseDtoApiResponse } from './models/EstadoClienteResponseDtoApiResponse';
export type { EstadoComponenteIngresoResponse } from './models/EstadoComponenteIngresoResponse';
export type { EstadoComponenteIngresoResponseApiResponse } from './models/EstadoComponenteIngresoResponseApiResponse';
export type { EstadoComponenteIngresoResponsePagedResponse } from './models/EstadoComponenteIngresoResponsePagedResponse';
export type { EstadoEmpleadoRequest } from './models/EstadoEmpleadoRequest';
export type { InformacionPreviaOrdenResponse } from './models/InformacionPreviaOrdenResponse';
export type { InformacionPreviaOrdenResponseApiResponse } from './models/InformacionPreviaOrdenResponseApiResponse';
export type { InspectorOrdenResponse } from './models/InspectorOrdenResponse';
export type { InspectorOrdenResponseApiResponse } from './models/InspectorOrdenResponseApiResponse';
export type { ListarCitasResponse } from './models/ListarCitasResponse';
export type { ListarCitasResponsePagedResponse } from './models/ListarCitasResponsePagedResponse';
export type { ListarClientesEmpresaDto } from './models/ListarClientesEmpresaDto';
export type { ListarClientesEmpresaDtoPagedResponse } from './models/ListarClientesEmpresaDtoPagedResponse';
export type { ListarClientesNaturalesDto } from './models/ListarClientesNaturalesDto';
export type { ListarClientesNaturalesDtoPagedResponse } from './models/ListarClientesNaturalesDtoPagedResponse';
export type { ListarDireccionesDto } from './models/ListarDireccionesDto';
export type { ListarDireccionesDtoPagedResponse } from './models/ListarDireccionesDtoPagedResponse';
export type { ListarDireccionesDtoPagedResponseApiResponse } from './models/ListarDireccionesDtoPagedResponseApiResponse';
export type { ListarOrdenesActivasDto } from './models/ListarOrdenesActivasDto';
export type { ListarOrdenesActivasDtoListApiResponse } from './models/ListarOrdenesActivasDtoListApiResponse';
export type { MantenimientoAsignadoGridResponse } from './models/MantenimientoAsignadoGridResponse';
export type { MantenimientoAsignadoGridResponsePagedResponse } from './models/MantenimientoAsignadoGridResponsePagedResponse';
export type { MantenimientoProgramadoResponse } from './models/MantenimientoProgramadoResponse';
export type { MarcaCreateUpdateRequest } from './models/MarcaCreateUpdateRequest';
export type { MisCitasResponse } from './models/MisCitasResponse';
export type { MisCitasResponsePagedResponse } from './models/MisCitasResponsePagedResponse';
export type { ObjectApiResponse } from './models/ObjectApiResponse';
export type { ObtenerDetalleCitaResponse } from './models/ObtenerDetalleCitaResponse';
export type { OrdenDetalladaResponse } from './models/OrdenDetalladaResponse';
export type { OrdenDetalladaResponseApiResponse } from './models/OrdenDetalladaResponseApiResponse';
export type { OrdenResponse } from './models/OrdenResponse';
export type { OrdenResponseApiResponse } from './models/OrdenResponseApiResponse';
export type { PaginationInfo } from './models/PaginationInfo';
export type { PaisDto } from './models/PaisDto';
export type { PaisDtoApiResponse } from './models/PaisDtoApiResponse';
export type { PaisDtoIEnumerableApiResponse } from './models/PaisDtoIEnumerableApiResponse';
export type { ProgramarMantenimientoRequest } from './models/ProgramarMantenimientoRequest';
export type { ProvinciaDto } from './models/ProvinciaDto';
export type { ProvinciaDtoApiResponse } from './models/ProvinciaDtoApiResponse';
export type { ProvinciaDtoIEnumerableApiResponse } from './models/ProvinciaDtoIEnumerableApiResponse';
export type { ReasignarTecnicoRequest } from './models/ReasignarTecnicoRequest';
export type { RegistrarEstadoComponenteRequest } from './models/RegistrarEstadoComponenteRequest';
export type { RegistrarEstadosComponentesRequest } from './models/RegistrarEstadosComponentesRequest';
export type { RegistroClienteEmpresaRequest } from './models/RegistroClienteEmpresaRequest';
export type { RegistroClienteEmpresaResponse } from './models/RegistroClienteEmpresaResponse';
export type { RegistroClienteEmpresaResponseApiResponse } from './models/RegistroClienteEmpresaResponseApiResponse';
export type { RegistroClienteNaturalRequest } from './models/RegistroClienteNaturalRequest';
export type { RegistroClienteNaturalResponse } from './models/RegistroClienteNaturalResponse';
export type { RegistroClienteNaturalResponseApiResponse } from './models/RegistroClienteNaturalResponseApiResponse';
export type { RestablecerPasswordRequest } from './models/RestablecerPasswordRequest';
export type { SolicitarRestablecimientoRequest } from './models/SolicitarRestablecimientoRequest';
export type { StringIEnumerableApiResponse } from './models/StringIEnumerableApiResponse';
export type { SubTipoActivoCreateUpdateRequest } from './models/SubTipoActivoCreateUpdateRequest';
export type { TecnicoSugeridoResponse } from './models/TecnicoSugeridoResponse';
export type { TipoActivoCreateUpdateRequest } from './models/TipoActivoCreateUpdateRequest';
export type { TipoClienteResponse } from './models/TipoClienteResponse';
export type { TipoClienteResponseApiResponse } from './models/TipoClienteResponseApiResponse';

export { ActivosService } from './services/ActivosService';
export { AdministradorService } from './services/AdministradorService';
export { AutenticacionService } from './services/AutenticacionService';
export { CatalogosService } from './services/CatalogosService';
export { CitasService } from './services/CitasService';
export { ClienteInternoService } from './services/ClienteInternoService';
export { ClientesService } from './services/ClientesService';
export { ContactosDirectosService } from './services/ContactosDirectosService';
export { ContactosEmpresaService } from './services/ContactosEmpresaService';
export { DireccionesService } from './services/DireccionesService';
export { GestionCitasService } from './services/GestionCitasService';
export { GestionClientesService } from './services/GestionClientesService';
export { GestionOrdenesService } from './services/GestionOrdenesService';
export { LocalidadesService } from './services/LocalidadesService';
export { MantenimientosProgramadosService } from './services/MantenimientosProgramadosService';
export { OrdenesService } from './services/OrdenesService';
